#! /usr/bin/env escript
main([Dir]) ->
    try 
	os:cmd("epmd&"),
	net_kernel:start([escript_test,shortnames]),
	[{acceptance,X,X},{unit,Y,Y},{modules,Z,Z}] = xpdojo:test_files(Dir)
    catch 
	Error:Reason ->
	    exit({Error,Reason,erlang:get_stacktrace()})
    end;
main(_) ->
    usage().
        
usage() ->
    io:format("usage: make_test <source directory name>\n"),
    halt(1).
